# 科幻地形可视化器配色方案
color_schemes:
  soviet_orange:
    primary: "#FF7F00"  # 主要颜色（标题、文本等）
    secondary: "#FF9F00"  # 次要颜色（高亮文本等）
    contour: "#FF7F00"  # 等高线颜色
    highlight_contour: "#FFFFFF"  # 高亮等高线颜色
    grid: "#3366FF"  # 网格颜色
    corner: "#FF7F00"  # 边角装饰颜色
    scan_line: "#FF7F00"  # 扫描线颜色
    cross: "#FF7F00"  # 网格交叉点颜色
    background: "#000000"  # 背景颜色
    colormap: "plasma"  # matplotlib颜色映射

  cyber_blue:
    primary: "#00FFFF"  # 主要颜色（标题、文本等）
    secondary: "#00CCFF"  # 次要颜色（高亮文本等）
    contour: "#00FFFF"  # 等高线颜色
    highlight_contour: "#FFFFFF"  # 高亮等高线颜色
    grid: "#0066FF"  # 网格颜色
    corner: "#00FFFF"  # 边角装饰颜色
    scan_line: "#00FFFF"  # 扫描线颜色
    cross: "#00FFFF"  # 网格交叉点颜色
    background: "#000000"  # 背景颜色
    colormap: "viridis"  # matplotlib颜色映射

  military_green:
    primary: "#33FF33"  # 主要颜色（标题、文本等）
    secondary: "#66FF66"  # 次要颜色（高亮文本等）
    contour: "#33FF33"  # 等高线颜色
    highlight_contour: "#FFFFFF"  # 高亮等高线颜色
    grid: "#006600"  # 网格颜色
    corner: "#33FF33"  # 边角装饰颜色
    scan_line: "#33FF33"  # 扫描线颜色
    cross: "#33FF33"  # 网格交叉点颜色
    background: "#000000"  # 背景颜色
    colormap: "inferno"  # matplotlib颜色映射

# 地图比例尺配置
map_scale:
  width_km: 10.61  # 地图宽度（公里）
  height_km: 10.61  # 地图高度（公里）
  max_elevation_km: 1.33  # 最大高度（公里）